const Discord = require("discord.js"); //FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE

exports.run = async (cleint, message, bot, args) => {//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE
  const voiceChannels = message.guild.channels.filter(c => c.type === "voice");//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE
  let sesliler = 0;
  for (const [id, voiceChannel] of voiceChannels)//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE
    sesliler += voiceChannel.members.size;//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE
  let uyeler = message.guild.memberCount;//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE
  let botlar = message.guild.members.filter(m => m.user.bot).size;//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE
  let toplamuye = uyeler - botlar;//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE

  const codebookxir = new Discord.RichEmbed()//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE
    .setColor(`RANDOM`)//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE
    .setTimestamp()
    .addField("Toplam Kullanıcılar **Rtx Bot**:", `**${uyeler}**`)//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE
    .addField("Üyeler **Rtx Bot**:", `**${toplamuye}**`)//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE
    .addField("Botlar **Rtx Bot**:", `**${botlar}**`)//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE
    .addField(//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE
      "Çevrimiçi üye sayısı     **Rtx Bot**",//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE
      `**${
        message.guild.members.filter(//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE
          m => !m.user.bot && m.user.presence.status !== "offline"//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE
        ).size
      }**`
    )
    .addField(
      "Çevrimdışı üye sayısı     **Rtx Bot**",//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE
      `**${
        message.guild.members.filter(off => off.presence.status === "offline")//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE
          .size
      }**`
    )
    .addField("Seslideki Üye Sayısı:", `**${sesliler}**`)//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE
    .addField(
      "Üyele Durumu:",
      `**${
        message.guild.members.filter(o => o.presence.status === "online").size//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE
      }** Çevrimiçi\n**${
        message.guild.members.filter(i => i.presence.status === "idle").size//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE
      }** Boşta\n**${
        message.guild.members.filter(dnd => dnd.presence.status === "dnd").size//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE
      }** Rahatsız Etmeyin\n**${
        message.guild.members.filter(off => off.presence.status === "offline")
          .size//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE
      }** Çevrimdışı-Gizli`//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE
    );
  message.channel.send(codebookxir);//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE
};
exports.conf = {//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE
  enabled: true,//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE
  guildOnly: false,//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE
  aliases: [],//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE
  permLevel: 0//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE//FYNX CODE
};
exports.help = {//FYNX CODE//FYNX CODE//FYNX CODE
  name: "kullanıcılar"//FYNX CODE
}